In [15]:
# Wczytanie danych
import pandas as pd

df_test = pd.read_csv("test.csv", sep=",", encoding="latin_1")
df = pd.read_csv("train.csv", sep=",", encoding="latin_1")

df.head()

   ItemID  Sentiment                                      SentimentText
0       1          0                       is so sad for my APL frie...
1       2          0                     I missed the New Moon trail...
2       3          1                            omg its already 7:30 :O
3       4          0            .. Omgaga. Im sooo  im gunna CRy. I'...
4       5          0           i think mi bf is cheating on me!!!   ...

In [16]:
df_test.head()

   ItemID                                      SentimentText
0       1                       is so sad for my APL frie...
1       2                     I missed the New Moon trail...
2       3                            omg its already 7:30 :O
3       4            .. Omgaga. Im sooo  im gunna CRy. I'...
4       5           i think mi bf is cheating on me!!!   ...

In [21]:
# Wybranie kolumn
df = df[["Sentiment","SentimentText"]]
df_test = df_test[["SentimentText"]]

df = df.rename(columns={"SentimentText": "New"})

df.head()

   Sentiment                                                New
0          0                       is so sad for my APL frie...
1          0                     I missed the New Moon trail...
2          1                            omg its already 7:30 :O
3          0            .. Omgaga. Im sooo  im gunna CRy. I'...
4          0           i think mi bf is cheating on me!!!   ...

In [27]:
df_new = pd.concat([df_test, df], axis=1)
df_new = df_new.drop(columns=["New"])
display(df_new)

                                            SentimentText  Sentiment
0                            is so sad for my APL frie...        0.0
1                          I missed the New Moon trail...        0.0
2                                 omg its already 7:30 :O        1.0
3                 .. Omgaga. Im sooo  im gunna CRy. I'...        0.0
4                i think mi bf is cheating on me!!!   ...        0.0
5                       or i just worry too much?                0.0
6                      Juuuuuuuuuuuuuuuuussssst Chillin!!        1.0
7              Sunny Again        Work Tomorrow  :-|  ...        0.0
8             handed in my uniform today . i miss you ...        1.0
9                hmmmm.... i wonder how she my number @-)        1.0
10                          I must think about positive..        0.0
11            thanks to all the haters up in my face a...        1.0
12                         this weekend has sucked so far        0.0
13                 jb isnt showing in australia any more!        0.0
14                                   ok thats it you win.        0.0
15          &lt;-------- This is the way i feel right ...        0.0
16          awhhe man.... I'm completely useless rt no...        0.0
17          Feeling strangely fine. Now I'm gonna go l...        1.0
18           HUGE roll of thunder just now...SO scary!!!!        0.0
19          I just cut my beard off. It's only been gr...        0.0
20                                   Very sad about Iran.        0.0
21                                          wompppp wompp        0.0
22          You're the only one who can see this cause...        1.0
23         &lt;---Sad level is 3. I was writing a mass...        0.0
24         ...  Headed to Hospitol : Had to pull out o...        0.0
25         BoRinG   ): whats wrong with him??     Plea...        0.0
26         can't be bothered. i wish i could spend the...        0.0
27         Feeeling like shit right now. I really want...        0.0
28                  goodbye exams, HELLO ALCOHOL TONIGHT         1.0
29         I didn't realize it was THAT deep. Geez giv...        0.0
...                                                   ...        ...
299959  @martin_lund_dk Now you're the one who's whini...        NaN
299960  @martin_mills Unfortunately need to push on wi...        NaN
299961  @martina_15 geez that was a quick one  good wo...        NaN
299962  @Martina_Nicole aah, i would love to but im up...        NaN
299963  @martinabel Very hot! Can't wait to see her done         NaN
299964  @martinamcbride can't wait to see it!  how do ...        NaN
299965  @martinamcbride have a wonderful sunday! prett...        NaN
299966  @martinamcbride I figured   Mine do that every...        NaN
299967  @martinamcbride i just saw ur new video, its a...        NaN
299968                  @martinamcbride I like that idea         NaN
299969  @MartinaR2100 just wait til next time he sees ...        NaN
299970     @MartinAronsen nah, I have to excerciceeeeeee         NaN
299971  @martinaustwick I question his methodology. An...        NaN
299972  @martinaxD lucky youuu!! yesterday i was studing         NaN
299973                             @martinboz thanks Boz         NaN
299974  @martinbrossman  MIL in same boat. Glad yours ...        NaN
299975  @martinbrossman Sorry to hear that Martin   Gi...        NaN
299976           @martincox p.s yousendit hasn't arrived         NaN
299977  @martincp I was putting a camcorder back to to...        NaN
299978  @martindave so cool! Thanks for including me o...        NaN
299979  @MartinDigon Five years on from &quot;free bre...        NaN
299980  @MartinDubow Thanks for following me on Twitter!         NaN
299981  @MartinDubow Welcome to my friends list and th...        NaN
299982                   @MartinDubow yeah and I envy u.         NaN
299983  @martine2323   It's ok,  I would rather stay o...        NaN
299984  @martine2323 'Morning, Petal - work brought me...        NaN
299985  @martinetrene Hello,little bird!  i finally st...        NaN
299986  @MartinezMayra I got u at work when I go buy o...        NaN
299987     @martinfaux He certainly gives good interview         NaN
299988  @martinfaux we've the feedback about our brows...        NaN

[299989 rows x 2 columns]

In [38]:
# Przygotowanie danych
import re

def norm1(row):
    return re.sub("[-()\"#/@;:<>{}`+=~|.!?,]",'',row["SentimentText"])

df_new["norm"] = df_new.apply(norm1, axis=1)
df_new = df_new.drop("SentimentText", axis=1)
display(df_new)

        Sentiment                                               norm
0             0.0                        is so sad for my APL friend
1             0.0                      I missed the New Moon trailer
2             1.0                              omg its already 730 O
3             0.0             Omgaga Im sooo  im gunna CRy I've b...
4             0.0           i think mi bf is cheating on me      ...
5             0.0                   or i just worry too much
6             1.0                   Juuuuuuuuuuuuuuuuussssst Chillin
7             0.0         Sunny Again        Work Tomorrow       ...
8             1.0        handed in my uniform today  i miss you a...
9             1.0                  hmmmm i wonder how she my number
10            0.0                        I must think about positive
11            1.0        thanks to all the haters up in my face a...
12            0.0                     this weekend has sucked so far
13            0.0              jb isnt showing in australia any more
14            0.0                                ok thats it you win
15            0.0               &lt This is the way i feel right now
16            0.0      awhhe man I'm completely useless rt now Fu...
17            1.0      Feeling strangely fine Now I'm gonna go li...
18            0.0              HUGE roll of thunder just nowSO scary
19            0.0      I just cut my beard off It's only been gro...
20            0.0                                Very sad about Iran
21            0.0                                      wompppp wompp
22            1.0      You're the only one who can see this cause...
23            0.0     &ltSad level is 3 I was writing a massive b...
24            0.0       Headed to Hospitol  Had to pull out of th...
25            0.0     BoRinG    whats wrong with him     Please t...
26            0.0     can't be bothered i wish i could spend the ...
27            0.0     Feeeling like shit right now I really want ...
28            1.0               goodbye exams HELLO ALCOHOL TONIGHT
29            0.0     I didn't realize it was THAT deep Geez give...
...           ...                                                ...
299959        NaN  martin_lund_dk Now you're the one who's whinin...
299960        NaN  martin_mills Unfortunately need to push on wit...
299961        NaN  martina_15 geez that was a quick one  good wor...
299962        NaN  Martina_Nicole aah i would love to but im upto...
299963        NaN    martinabel Very hot Can't wait to see her done
299964        NaN  martinamcbride can't wait to see it  how do i ...
299965        NaN  martinamcbride have a wonderful sunday pretty ...
299966        NaN  martinamcbride I figured   Mine do that every ...
299967        NaN  martinamcbride i just saw ur new video its awe...
299968        NaN                   martinamcbride I like that idea
299969        NaN  MartinaR2100 just wait til next time he sees y...
299970        NaN       MartinAronsen nah I have to excerciceeeeeee
299971        NaN  martinaustwick I question his methodology And ...
299972        NaN     martinaxD lucky youuu yesterday i was studing
299973        NaN                              martinboz thanks Boz
299974        NaN  martinbrossman  MIL in same boat Glad yours is...
299975        NaN  martinbrossman Sorry to hear that Martin   Giv...
299976        NaN             martincox ps yousendit hasn't arrived
299977        NaN  martincp I was putting a camcorder back to tog...
299978        NaN  martindave so cool Thanks for including me on ...
299979        NaN  MartinDigon Five years on from &quotfree brekk...
299980        NaN    MartinDubow Thanks for following me on Twitter
299981        NaN  MartinDubow Welcome to my friends list and tha...
299982        NaN                     MartinDubow yeah and I envy u
299983        NaN  martine2323   It's ok  I would rather stay on ...
299984        NaN  martine2323 'Morning Petal  work brought me he...
299985        NaN  martinetrene Hellolittle bird  i finally start...
299986        NaN  MartinezMayra I got u at work when I go buy on...
299987        NaN      martinfaux He certainly gives good interview
299988        NaN  martinfaux we've the feedback about our browse...

[299989 rows x 2 columns]

In [39]:
# Wektoryzacja
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(binary=True)
norm = df_new["norm"]
cv.fit(norm)
X_transform = cv.transform(norm)

y = df_new[['Sentiment']].iloc[0:300]


X.shape

(299989, 284637)

In [35]:
display(X)

<299989x284637 sparse matrix of type '<class 'numpy.int64'>'
	with 3566531 stored elements in Compressed Sparse Row format>

In [32]:
# Podział danych
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split as tts

X_train, X_test, y_train, y_test = tts(X, y)

num_classes = 2

y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

Using TensorFlow backend.

ValueError: Found input variables with inconsistent numbers of samples: [299989, 300]

In [7]:
# Tworzenie sieci neuronowej Keras
from keras import models
from keras.layers import Dense, Dropout

model = models.Sequential()
model.add(Dense(100, activation="relu", input_shape=(284637,)))
model.add(Dropout(0.3))
model.add(Dense(100, activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(num_classes, activation="sigmoid"))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 100)               11707400
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0
_________________________________________________________________
dense_2 (Dense)              (None, 100)               10100
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 202
=================================================================
Total params: 11,717,702
Trainable params: 11,717,702
Non-trainable params: 0
_________________________________________________________________

In [8]:
# Kompilacja modelu
model.compile(
    optimizer = "adam",
    loss = "binary_crossentropy",
    metrics = ["accuracy"]
)

In [9]:
# Trenowanie modelu

results = model.fit(
    X_train, y_train,
    epochs = 2,
    batch_size = 256,
    validation_data = (X_test, y_test)
)

Train on 74991 samples, validate on 24998 samples
Epoch 1/2
74991/74991 [==============================] - 143s 2ms/step - loss: 0.5259 - acc: 0.7368 - val_loss: 0.4789 - val_acc: 0.7674
Epoch 2/2
74991/74991 [==============================] - 141s 2ms/step - loss: 0.3330 - acc: 0.8575 - val_loss: 0.5264 - val_acc: 0.7594

In [10]:
# Sprawdzenie skuteczności 

score = model.evaluate(X_test, y_test, verbose=0)
print("Test loss: ", score[0])
print("Test accuracy: ", score[1])

Test loss:  0.5263606435642766
Test accuracy:  0.7594407552604209

In [13]:
# Predykcja danych testowych
results1 = model.predict(X_2, batch_size=256, verbose=0, steps=None)

ValueError: Error when checking input: expected dense_1_input to have shape (117073,) but got array with shape (284637,)

In [12]:
#submission = pd.DataFrame({"ItemID":df_test["ItemID"], "Sentiment":results})
#filename = "Twits Prediction 1.csv"
#submission.to_csv(filename, index=False)

In [ ]:
file = 'results1.csv'
results_to_file = pandas.DataFrame({'ItemID':df['ItemID'], 'Sentiment':predictions_to_file})
results_to_file.to_csv(file, index=False)